fix: jupyter labextension develop . --overwrite not working
The command above started failing for me recently with a strange
vague error:

ModuleNotFoundError: There is no labextension at .. Errors encountered: [TypeError("the 'package' argument is required to perform a relative import for '.'")]

Generally, globus_jupyterlab/ seemed like it would autogenerate most
times just fine without any intervention. However, in this case it wasn't
for me, and the `jupyter labextension develop` command searches under the
package name + __init__.py to discover whether the following item exists:

_jupyter_labextension_paths

And uses that to determine whether the folder you're trying to install is
a "real" labextension package, otherwise it fails with the vague error
above.

Adding those items should fix this from happening again